### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by brandongalbraith** [etnguyen03/docker-tubeup#187]
Is this still actively maintained @etnguyen03? Saw some PRs that haven't been merged up yet and dependabot is paused due to inactivity. Apologies for opening an issue, did not see contact info to reach out OOB.

**Comment by etnguyen03** [comment]
I still use it and kind of maintain it, although the current open Dependabot PRs are incompatible so I haven't merged them. Just pushed an update.
